services:
  nginx:
    container_name: sharex-nginx
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - images:/var/www
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: sharex-ftpd
    volumes:
      - images:/home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=${DOMAIN}
      - FTP_USER_NAME=${FTP_USER}
      - FTP_USER_PASS=${FTP_PASSWORD}
      - FTP_USER_HOME=/home/ftpusers
    restart: unless-stopped

volumes:
  images: