FROM nginx:stable-alpine3.20-slim

COPY nginx.conf.template /etc/nginx/sites-available/

COPY --chmod=755 nginx-entrypoint.sh /etc/nginx/sites-available/

ENTRYPOINT ["/etc/nginx/sites-available/nginx-entrypoint.sh"]